enabled: true
custom_logo:
  user/themes/hola/images/logo/logo.png:
    name: logo.png
    type: image/png
    size: 5238
    path: user/themes/hola/images/logo/logo.png
footer-text: 'Â© dharavi.org 2023'
footer-design: '<a href="https://www.urbz.net/">urbz.net</a>'
footer-social:
  -
    socialIconClass: 'fa fa-facebook-square'
    socialIconText: Facebook
    socialIconLink: 'https://www.facebook.com/devlom'
  -
    socialIconClass: 'fa fa-twitter'
    socialIconText: Twitter
    socialIconLink: 'https://twitter.com/devlomthemes'
  -
    socialIconClass: 'fa fa-instagram'
    socialIconText: Instagram
    socialIconLink: '#0'
  -
    socialIconClass: 'fa fa-behance'
    socialIconText: Behance
    socialIconLink: '#0'
  -
    socialIconClass: 'fa fa-pinterest'
    socialIconText: Pinterest
    socialIconLink: '#0'
footer-additional-text: '<a href="https://www.nyuad.io/">Engineers for Social Impact 2023</a>'
